services:
  app:
    container_name: cpeevo_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - cpeevo_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=web"

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - cpeevo_network

networks:
  cpeevo_network:
    driver: bridge