global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-app'
    kubernetes_sd_configs:
      - role: endpoints

    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: (.+):(\d+)
        replacement: $1:8080