apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpeevo-backend
  labels:
    app: cpeevo-backend
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5m"

spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpeevo-backend
  template:
    metadata:
      labels:
        app: cpeevo-backend
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: cpeevo-backend
      containers:
      - name: cpeevo-backend
        image: encalls/cpeevo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: cpeevo-secrets
              key: MONGO_URI
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: cpeevo-config
              key: DATABASE_NAME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cpeevo-secrets
              key: SECRET_KEY
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: cpeevo-config
              key: GIN_MODE
        - name: ORIGIN_URL
          valueFrom:
            configMapKeyRef:
              name: cpeevo-config
              key: ORIGIN_URL
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          periodSeconds: 5